twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        instance_name: '%env(default:app.instance_name_default:INSTANCE_NAME)%'
        instance_sysadmin_email: '%env(default::INSTANCE_SYSADMIN_EMAIL)%'
    paths:
        '%kernel.project_dir%/templates-local':  ~
    form_themes: ['form_div_layout.html.twig','form_theme.html.twig']