twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # Some config variables - see docs/hosting/configuration-options.md
        instance_name: '%env(default:app.instance_name_default:INSTANCE_NAME)%'
        instance_sysadmin_email: '%env(default::INSTANCE_SYSADMIN_EMAIL)%'
        instance_read_only: '%env(bool:INSTANCE_READ_ONLY)%'
        instance_federation: '%env(bool:INSTANCE_FEDERATION)%'
        # Some common display options used in UI and defined here so available on multiple templates
        event_list_description_truncate_limit: 400
        event_list_description_truncate_more: "..."
        event_list_description_truncate_whole_words: false
        # Some constants - from src/Constants.php
        PRIVACY_LEVEL_PUBLIC: 0;
        PRIVACY_LEVEL_ONLY_FOLLOWERS: 5000
        PRIVACY_LEVEL_PRIVATE: 10000
    paths:
        '%kernel.project_dir%/templates-local':  ~
    form_themes: ['form_div_layout.html.twig','form_theme.html.twig']
