name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: php-cs-fixer:2.17.2

      - name: PHP in src; PSR1 & PSR2
        run: php-cs-fixer -v --dry-run --using-cache=no fix src
